
POST http://localhost:8000/api/pesapal/auth/request-token HTTP/1.1

###
POST http://localhost:8000/api/pesapal/ipn/register HTTP/1.1


###
POST https://tunes.digitalhive.co.ke/api/pesapal/transactions/submit-order HTTP/1.1
content-type: application/json

{
     "order_id": "109156be-c4fb-41ea-b1b4-efe1671c5836",
     "currency": "KES",
     "amount": 75000.00,
     "description": "Payment description goes here",
     "callback_url": "https://tunes.digitalhive.co.ke/api/pesapal/transactions/payment-completed",
    // "notification_id": "b47aaa49-1fd5-48c6-9b77-e02116131ab4",
     "billing_address": {
         "email_address": "john.doe@example.com",
         "phone_number": "",
         "country_code": "",
         "first_name": "John",
         "middle_name": "",
         "last_name": "Doe",
         "line_1": "",
         "line_2": "",
         "city": "",
         "state": "",
         "postal_code": "",
         "zip_code": ""
     }
 }


###
GET https://pesapalapi.samitune.com/api/transactions/023dafc2-92a4-4816-a786-de90269669a4/status HTTP/1.1


###
GET http://localhost:8000/api/pesapal/ipn/list HTTP/1.1